/* This class has been auto-generated Please DO NOT edit this file! */
package org.nightlabs.jfire.prop.cache.id;

import java.io.UnsupportedEncodingException;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.text.ParseException;
import java.util.StringTokenizer;

import javax.annotation.Generated;

import org.nightlabs.jdo.ObjectID;
import org.nightlabs.jfire.prop.cache.FetchGroupsPartSet;
import org.nightlabs.jfire.prop.id.PropertySetID;


/**
 * The JDO object id class for {@link org.nightlabs.jfire.prop.cache.DetachedPropertySet}.
 * <p>This class was auto-generated.</p>
 */
@SuppressWarnings("deprecation")
@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
public class DetachedPropertySetID
implements ObjectID
{
	/**
	 * The serial version uid of this class.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	private static final long serialVersionUID = 5634403687489724072L;

	/**
	 * The values of all fields are URL encoded in UTF-8.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public static final String ENCODING = "UTF-8"; //$NON-NLS-1$

	/**
	 * The object id URL prefix.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	private static final String JDO_PREFIX = "jdo"; //$NON-NLS-1$

	/**
	 * The object id URL prefix separator.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	private static final char JDO_PREFIX_SEPARATOR = '/';

	/**
	 * The object id URL class separator.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	private static final char CLASS_SEPARATOR = '?';

	/**
	 * The object id URL tokenizer separators.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	private static final String SEPARATORS_FOR_TOKENIZER = "/?=&"; //$NON-NLS-1$

	/**
	 * The object id URL key/value separator.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	private static final String SEPARATOR_KEY_VALUE = "="; //$NON-NLS-1$

	/**
	 * The object id URL entry separator.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	private static final String SEPARATOR_ENTRY = "&"; //$NON-NLS-1$

	/**
	 * The radix that is used for encoding/decoding field values of numeric IDs (byte, short, int, long).
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	private static final int RADIX = 36;

	/**
	 * Primary key field organisationID.
	 * Declared as primary key field in {@link org.nightlabs.jfire.prop.cache.DetachedPropertySet}.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public java.lang.String organisationID;

	/**
	 * Primary key field propertySetID.
	 * Declared as primary key field in {@link org.nightlabs.jfire.prop.cache.DetachedPropertySet}.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public long propertySetID;

	/**
	 * Primary key field fetchGroups_part1.
	 * Declared as primary key field in {@link org.nightlabs.jfire.prop.cache.DetachedPropertySet}.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public java.lang.String fetchGroups_part1;

	/**
	 * Primary key field fetchGroups_part2.
	 * Declared as primary key field in {@link org.nightlabs.jfire.prop.cache.DetachedPropertySet}.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public java.lang.String fetchGroups_part2;

	/**
	 * Primary key field fetchGroups_part3.
	 * Declared as primary key field in {@link org.nightlabs.jfire.prop.cache.DetachedPropertySet}.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public java.lang.String fetchGroups_part3;

	/**
	 * Primary key field maxFetchDepth.
	 * Declared as primary key field in {@link org.nightlabs.jfire.prop.cache.DetachedPropertySet}.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public int maxFetchDepth;

	/**
	 * Create a new empty instance of DetachedPropertySetID.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public DetachedPropertySetID()
	{
	}

	/**
	 * Create a new instance of DetachedPropertySetID.
	 * This is done by parsing the <code>keyStr</code> that has been created
	 * by {@link #toString()} and setting all fields to the values from the string.
	 * <p>
	 * This means, the following code will create a copy of this class:<br/><br/>
	 * <code>DetachedPropertySetID newDetachedPropertySetID = new DetachedPropertySetID(oldDetachedPropertySetID.toString());</code>
	 * </p>
	 * @param keyStr A String formatted as "jdo/{className}?{field0}={value0}&amp;{field1}={value1}...&amp;{fieldN}={valueN}"
	 *     where all values are url encoded using {@link #ENCODING}.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public DetachedPropertySetID(final String keyStr)
	throws ParseException, SecurityException,
			NoSuchFieldException, IllegalArgumentException,
			IllegalAccessException, NoSuchMethodException,
			InstantiationException, InvocationTargetException
	{
		Class<? extends DetachedPropertySetID> clazz = this.getClass();

		StringTokenizer st = new StringTokenizer(keyStr, SEPARATORS_FOR_TOKENIZER, true);
		String jdoPrefix = st.nextToken();
		if (!JDO_PREFIX.equals(jdoPrefix))
			throw new ParseException(
					"keyStr \""+ //$NON-NLS-1$
					keyStr+
					"\" does not start with jdo prefix \""+ //$NON-NLS-1$
					JDO_PREFIX+
					"\"!", 0); //$NON-NLS-1$
		if (!st.hasMoreTokens() || st.nextToken().charAt(0) != JDO_PREFIX_SEPARATOR)
			throw new ParseException(
					"keyStr \""+ //$NON-NLS-1$
					keyStr+
					"\" is missing separator \""+ //$NON-NLS-1$
					JDO_PREFIX_SEPARATOR+
					"\" after jdo prefix!", 0); //$NON-NLS-1$

		String className = st.nextToken();
		if (!className.equals(clazz.getName()))
			throw new ParseException(
					"keyStr defines class \""+ //$NON-NLS-1$
					className+
					"\", but this is an instance of \""+ //$NON-NLS-1$
					clazz.getName()+
					"\"!", 0); //$NON-NLS-1$

		if (!st.hasMoreTokens() || st.nextToken().charAt(0) != CLASS_SEPARATOR)
			throw new ParseException(
					"keyStr \""+ //$NON-NLS-1$
					keyStr+
					"\" is missing separator \""+ //$NON-NLS-1$
					CLASS_SEPARATOR+
					"\" after class!", 0); //$NON-NLS-1$

		while (st.hasMoreTokens()) {
			String key = st.nextToken();
			String valStr = ""; //$NON-NLS-1$
			if (st.hasMoreTokens()) {
				String sep = st.nextToken();
				if (!SEPARATOR_KEY_VALUE.equals(sep))
					throw new ParseException(
							"Expected \""+ //$NON-NLS-1$
							SEPARATOR_KEY_VALUE+
							"\", but found \""+ //$NON-NLS-1$
							sep+
							"\"!", 0); //$NON-NLS-1$

				if (st.hasMoreTokens()) {
					valStr = st.nextToken();
					if (SEPARATOR_ENTRY.equals(valStr)) {
						sep = valStr;
						valStr = ""; //$NON-NLS-1$
					}
					else
						try {
							valStr = URLDecoder.decode(valStr, ENCODING);
						} catch (UnsupportedEncodingException e) {
							e.printStackTrace();
							throw new RuntimeException(e);
						}
				}
				if (!SEPARATOR_ENTRY.equals(sep)) {
					if (st.hasMoreTokens()) {
						sep = st.nextToken();
						if (!SEPARATOR_ENTRY.equals(sep))
							throw new ParseException(
									"Expected \""+ //$NON-NLS-1$
									SEPARATOR_ENTRY+
									"\", but found \""+ //$NON-NLS-1$
									sep+"\"!", 0); //$NON-NLS-1$
					}
				} // if (!SEPARATOR_ENTRY.equals(val)) {
			} // if (st.hasMoreTokens()) {
			Field field = clazz.getField(key);
			Class<?> fieldType = field.getType();
			if (valStr == null) {
				if (!fieldType.isPrimitive())
					field.set(this, null);
				else {
					if (boolean.class.isAssignableFrom(fieldType))
						field.set(this, Boolean.FALSE);
					else if (char.class.isAssignableFrom(fieldType))
						field.set(this, Character.valueOf((char)0));
					else // for all other primitives - i.e. byte, short, int, long, float, double
						field.set(this, Byte.valueOf((byte)0));
				}
			}
			else {
				Object val = null;
				if (String.class.isAssignableFrom(fieldType))
					val = valStr;
				else if (boolean.class.isAssignableFrom(fieldType))
					val = Boolean.valueOf(valStr);
				else if (char.class.isAssignableFrom(fieldType))
					val = Character.valueOf(valStr.charAt(0));
				else if (byte.class.isAssignableFrom(fieldType))
					val = Byte.valueOf(valStr, RADIX);
				else if (short.class.isAssignableFrom(fieldType))
					val = Short.valueOf(valStr, RADIX);
				else if (int.class.isAssignableFrom(fieldType))
					val = Integer.valueOf(valStr, RADIX);
				else if (long.class.isAssignableFrom(fieldType))
					val = Long.valueOf(valStr, RADIX);
				else
					throw new IllegalArgumentException(
							"Type "+ //$NON-NLS-1$
							fieldType.getName()+
							" of member "+ //$NON-NLS-1$
							key+
							" is not unsupported!"); //$NON-NLS-1$
				field.set(this, val);
			}
		}
	}

	/**
	 * Create a string representation of this object id.
	 * <p>
	 * JDO expects the result of this method to be compatible with the constructor
	 * {@link #DetachedPropertySetID(String)}.
	 * This method takes all the primary-key-fields and encodes them with their name
	 * and their value.
	 * </p>
	 * @return a string representation of this object id.
	 * @see java.lang.Object#toString()
	 */
	@Override
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public String toString()
	{
		StringBuffer sb = new StringBuffer(JDO_PREFIX);
		sb.append(JDO_PREFIX_SEPARATOR);
		sb.append(this.getClass().getName());
		sb.append(CLASS_SEPARATOR);

		try {
			sb.append("organisationID="); //$NON-NLS-1$
			sb.append(URLEncoder.encode(String.valueOf(organisationID), ENCODING));
			sb.append('&');
			sb.append("propertySetID="); //$NON-NLS-1$
			sb.append(URLEncoder.encode(Long.toString(propertySetID, RADIX), ENCODING));
			sb.append('&');
			sb.append("fetchGroups_part1="); //$NON-NLS-1$
			sb.append(URLEncoder.encode(String.valueOf(fetchGroups_part1), ENCODING));
			sb.append('&');
			sb.append("fetchGroups_part2="); //$NON-NLS-1$
			sb.append(URLEncoder.encode(String.valueOf(fetchGroups_part2), ENCODING));
			sb.append('&');
			sb.append("fetchGroups_part3="); //$NON-NLS-1$
			sb.append(URLEncoder.encode(String.valueOf(fetchGroups_part3), ENCODING));
			sb.append('&');
			sb.append("maxFetchDepth="); //$NON-NLS-1$
			sb.append(URLEncoder.encode(Integer.toString(maxFetchDepth, RADIX), ENCODING));
		} catch (UnsupportedEncodingException e) {
			throw new RuntimeException(
					"Encoding failed with encoding " + //$NON-NLS-1$
					ENCODING, e);
		}
		return sb.toString();
	}

	/**
	 * Compare all primary key fields (according to the JDO spec).
	 * @param obj the reference object with which to compare.
	 * @return <code>true</code> if all primary key fields are equal - <code>false</code> otherwise.
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public boolean equals(Object obj)
	{
		if(this == obj)
			return true;
		if(obj == null)
			return false;
		if(getClass() != obj.getClass())
			return false;
		DetachedPropertySetID other = (DetachedPropertySetID) obj;
		if(organisationID == null) {
			if(other.organisationID != null)
				return false;
		} else if(!organisationID.equals(other.organisationID))
			return false;
		if(propertySetID != other.propertySetID)
			return false;
		if(fetchGroups_part1 == null) {
			if(other.fetchGroups_part1 != null)
				return false;
		} else if(!fetchGroups_part1.equals(other.fetchGroups_part1))
			return false;
		if(fetchGroups_part2 == null) {
			if(other.fetchGroups_part2 != null)
				return false;
		} else if(!fetchGroups_part2.equals(other.fetchGroups_part2))
			return false;
		if(fetchGroups_part3 == null) {
			if(other.fetchGroups_part3 != null)
				return false;
		} else if(!fetchGroups_part3.equals(other.fetchGroups_part3))
			return false;
		if(maxFetchDepth != other.maxFetchDepth)
			return false;
		return true;
	}

	/**
	 * Returns a hash code for this object id. The hash code for a
	 * object id object is computed by combining the hash codes of
	 * all primary key fields.
	 * @return a hash code for this object.
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((organisationID == null) ? 0 : organisationID.hashCode());
		result = prime * result + (int) (propertySetID ^ (propertySetID >>> 32));
		result = prime * result + ((fetchGroups_part1 == null) ? 0 : fetchGroups_part1.hashCode());
		result = prime * result + ((fetchGroups_part2 == null) ? 0 : fetchGroups_part2.hashCode());
		result = prime * result + ((fetchGroups_part3 == null) ? 0 : fetchGroups_part3.hashCode());
		result = prime * result + maxFetchDepth;
		return result;
	}

	public String[] getFetchGroups() {
		return new FetchGroupsPartSet(fetchGroups_part1, fetchGroups_part2, fetchGroups_part3).getFetchGroups();
	}

	/**
	 * Create a new object id instance.
	 * @param organisationID The primary key field organisationID.
	 * @param propertySetID The primary key field propertySetID.
	 * @param fetchGroups_part1 The primary key field fetchGroups_part1.
	 * @param fetchGroups_part2 The primary key field fetchGroups_part2.
	 * @param fetchGroups_part3 The primary key field fetchGroups_part3.
	 * @param maxFetchDepth The primary key field maxFetchDepth.
	 * @return a newly created instance of <code>DetachedPropertySetID</code>
	 *     with the primary-key fields set to the given parameters.
	 */
	@Generated("org.nightlabs.eclipse.sdk.jdo.ObjectIdGenerator")
	private static DetachedPropertySetID create(String organisationID, long propertySetID, String fetchGroups_part1, String fetchGroups_part2, String fetchGroups_part3, int maxFetchDepth)
	{
		DetachedPropertySetID n = new DetachedPropertySetID();
		n.organisationID = organisationID;
		n.propertySetID = propertySetID;
		n.fetchGroups_part1 = fetchGroups_part1;
		n.fetchGroups_part2 = fetchGroups_part2;
		n.fetchGroups_part3 = fetchGroups_part3;
		n.maxFetchDepth = maxFetchDepth;
		return n;
	}

	public static DetachedPropertySetID create(PropertySetID propertySetID, String[] fetchGroups, int maxFetchDepth)
	{
		FetchGroupsPartSet fetchGroupsPartSet = new FetchGroupsPartSet(fetchGroups);
		return create(propertySetID, fetchGroupsPartSet, maxFetchDepth);
	}

	public static DetachedPropertySetID create(PropertySetID propertySetID, FetchGroupsPartSet fetchGroupsPartSet, int maxFetchDepth)
	{
		return create(
				propertySetID.organisationID,
				propertySetID.propertySetID,
				fetchGroupsPartSet.getFetchGroups_part1(),
				fetchGroupsPartSet.getFetchGroups_part2(),
				fetchGroupsPartSet.getFetchGroups_part3(),
				maxFetchDepth
		);
	}
}
