/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.testsuite;

/**
 * Remote interface for jfire/ejb/JFireTestSuite/JFireTestManager.
 * @build-nightlabs.xml generated
 */
public interface JFireTestManager
   extends javax.ejb.EJBObject
{
   /**
    * This method is called by the datastore initialisation mechanism. It runs all {@link TestSuite}s.
    * @throws Exception When something went wrong.
    */
   public void initialise(  )
      throws java.lang.Exception, java.rmi.RemoteException;

}
