/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.testsuite;

/**
 * Local interface for jfire/ejb/JFireTestSuite/JFireTestManager.
 * @build-nightlabs.xml generated
 */
public interface JFireTestManagerLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * This method is called by the datastore initialisation mechanism. It runs all {@link TestSuite}s.
    * @throws Exception When something went wrong.
    */
   public void initialise(  ) throws java.lang.Exception;

}
