/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.testsuite;

/**
 * Local home interface for jfire/ejb/JFireTestSuite/JFireTestManager.
 * @build-nightlabs.xml generated
 */
public interface JFireTestManagerLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/jfire/ejb/JFireTestSuite/JFireTestManagerLocal";
   public static final String JNDI_NAME="jfire/ejb/JFireTestSuite/JFireTestManagerLocal";

   public org.nightlabs.jfire.testsuite.JFireTestManagerLocal create()
      throws javax.ejb.CreateException;

}
