/*
 * Generated by XDoclet - Do not edit!
 */
package org.nightlabs.jfire.testsuite;

/**
 * Home interface for jfire/ejb/JFireTestSuite/JFireTestManager.
 * @build-nightlabs.xml generated
 */
public interface JFireTestManagerHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/jfire/ejb/JFireTestSuite/JFireTestManager";
   public static final String JNDI_NAME="jfire/ejb/JFireTestSuite/JFireTestManager";

   public org.nightlabs.jfire.testsuite.JFireTestManager create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
