/**
 * 
 */
package org.nightlabs.jfire.base.person.edit.blockbased.special;

import org.eclipse.swt.SWT;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.events.SelectionListener;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Control;
import org.nightlabs.base.composite.LabeledText;
import org.nightlabs.base.exceptionhandler.ExceptionHandlerRegistry;
import org.nightlabs.jfire.base.JFireBasePlugin;
import org.nightlabs.jfire.base.prop.StructLocalDAO;
import org.nightlabs.jfire.base.prop.edit.DataFieldEditor;
import org.nightlabs.jfire.base.prop.edit.blockbased.DataBlockEditor;
import org.nightlabs.jfire.base.prop.edit.blockbased.DataBlockEditorChangedListener;
import org.nightlabs.jfire.base.prop.edit.blockbased.DataBlockWizardPage;
import org.nightlabs.jfire.person.Person;
import org.nightlabs.jfire.person.PersonStruct;
import org.nightlabs.jfire.prop.TextDataField;

/**
 * @author alex
 *
 */
public class PersonPersonalDataWizardPage 
extends DataBlockWizardPage 
implements DataBlockEditorChangedListener 
{
	private LabeledText displayName;
	private Button autoCreateDisplayName;
	/**
	 * @param pageName
	 */
	public PersonPersonalDataWizardPage(String pageName, String title, Person person) {
		super(pageName, title, StructLocalDAO.sharedInstance().getStructLocal(Person.class), person, PersonStruct.PERSONALDATA);
	}

	/**
	 * 
	 * @see org.eclipse.jface.dialogs.IDialogPage#createControl(org.eclipse.swt.widgets.Composite)
	 */
	public Control createPageContents(Composite parent) {
		createWrapper(parent);
		
		displayName = new LabeledText(getWrapperComp(), JFireBasePlugin.getResourceString("person.edit.wizard.pages.PersonalDataPage.labels.displayName"));
		GridData displayNameGD = new GridData();
//		displayNameGD.grabExcessHorizontalSpace = true;
		displayNameGD.horizontalAlignment = GridData.FILL;
//		displayNameGD.widthHint = 200;
		displayNameGD.grabExcessHorizontalSpace = true;
		displayName.setLayoutData(displayNameGD);
		
		autoCreateDisplayName = new Button(getWrapperComp(), SWT.CHECK);
		GridData autoCreateDisplayNameGD = new GridData();
//		autoCreateDisplayNameGD.grabExcessHorizontalSpace = true;
//		autoCreateDisplayNameGD.horizontalAlignment = GridData.FILL;
		autoCreateDisplayName.setLayoutData(autoCreateDisplayNameGD);
		autoCreateDisplayName.setText(JFireBasePlugin.getResourceString("person.edit.wizard.pages.PersonalDataPage.labels.autoCreateDisplayName"));
		autoCreateDisplayName.addSelectionListener(
			new SelectionListener() {

				public void widgetSelected(SelectionEvent arg0) {
					displayName.getTextControl().setEnabled(!autoCreateDisplayName.getSelection());
				}
				public void widgetDefaultSelected(SelectionEvent arg0) {
				}
			}
		);
		autoCreateDisplayName.setSelection(true);
		displayName.getTextControl().setEnabled(false);
		
		Composite dummy = new Composite(getWrapperComp(),SWT.NONE);
		GridData dummyGD = new GridData();
		dummyGD.heightHint = 10;
		dummy.setLayoutData(dummyGD);
		
		setPropDataBlockEditorColumnHint(1);
		createPropDataBlockEditors();
		getPropDataBlockEditor().addPropDataBlockEditorChangedListener(this);
		pageChanged();
		return getWrapperComp();
	}

	protected void pageChanged() {
		try {
			updatePerson();
			TextDataField name = (TextDataField)getPropDataBlock().getDataField(PersonStruct.PERSONALDATA_NAME);
			TextDataField firstName = (TextDataField)getPropDataBlock().getDataField(PersonStruct.PERSONALDATA_FIRSTNAME);
			displayName.getTextControl().setText(getProp().getDisplayName());

			if (firstName.isEmpty())
				updateStatus(JFireBasePlugin.getResourceString("person.edit.wizard.pages.PersonalDataPage.errormessage.specifyFirstName"));
			else if (name.isEmpty())
				updateStatus(JFireBasePlugin.getResourceString("person.edit.wizard.pages.PersonalDataPage.errormessage.specifyName"));
			else
				updateStatus(null);
		} catch (Throwable t) {
			ExceptionHandlerRegistry.syncHandleException(t);
		}
	}
	
	/**
	 * Overrides and additionally sets displayName and autoCreateDisplayName.
	 * 
	 * @see org.nightlabs.jfire.base.person.edit.blockbased.PersonCompoundDataBlockWizardPage#updatePerson()
	 */
	public void updatePerson() {
		super.updateProp();
		getProp().setAutoGenerateDisplayName(autoCreateDisplayName.getSelection());
		getProp().setDisplayName(displayName.getTextControl().getText(), StructLocalDAO.sharedInstance().getStructLocal(Person.class));
	}

	public void propDataBlockEditorChanged(DataBlockEditor dataBlockEditor, DataFieldEditor dataFieldEditor) {
		pageChanged();
	}
	
}
